[package]
name = "rustformer_websocket"
version = "0.1.0"
edition = "2021"

[dependencies]
llm = "0.1.1"
rand = "0.8.5"
websocket = "0.27.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[profile.dev.package.ggml-sys]
opt-level = 3
